Fatal error: app/install is outdated. You need to re-upload app/install folder with the one from Chevereto 1.4.1
Getting Fetal error while upgrade from 1.4.0 to 1.4.1
Fatal error: app/install is outdated. You need to re-upload app/install folder with the one from Chevereto 1.4.1